# Generated by Django 2.2.6 on 2019-10-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='auth_token'),
        ),
    ]
